/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.freemarker:freemarker:2.3.19")
    api("org.apache.logging.log4j:log4j-core:2.17.2")
    api("jgraph:jgraph:5.13.0.0")
    api("org.databene:databene-benerator:0.5.9-SR1")
    api("org.databene:databene-commons:0.4.9-SR1")
    api("org.databene:databene-webdecs:0.4.9-SR1")
    api("org.swinglabs:swing-layout:1.0.3")
    api("commons-logging:commons-logging:1.1.1")
    api("mysql:mysql-connector-java:8.0.30")
    api("org.perf4j:perf4j:0.9.16")
    api("org.testng:testng:7.7.1")
}

group = "com.brc"
version = "0.0.1-SNAPSHOT"
description = "white-mercury-dg"
java.sourceCompatibility = JavaVersion.VERSION_1_7

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.named<Test>("test") {
    useTestNG()
}
