/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

 pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

rootProject.name = "white-mercury-dg"
